# Generated by Django 6.0.4 on 2026-06-23 17:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('animals', '0003_animalnote'),
        ('farms', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProductionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('session', models.CharField(choices=[('morning', 'Morning'), ('afternoon', 'Afternoon'), ('evening', 'Evening')], max_length=20, verbose_name='session')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='quantity (liters)')),
                ('quality', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('poor', 'Poor')], default='good', max_length=20, verbose_name='quality')),
                ('fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='fat percentage')),
                ('snf_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='SNF percentage')),
                ('protein_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='protein percentage')),
                ('lactose_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='lactose percentage')),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='temperature (°C)')),
                ('price_per_liter', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='price per liter')),
                ('total_value', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True, verbose_name='total value')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal', models.ForeignKey(limit_choices_to={'gender': 'female'}, on_delete=django.db.models.deletion.CASCADE, related_name='milk_production_logs', to='animals.animal', verbose_name='animal')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_production_logs', to='farms.farm', verbose_name='farm')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_milk_logs', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'milk production log',
                'verbose_name_plural': 'milk production logs',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['animal', 'date'], name='productions_animal__ae5cc4_idx'), models.Index(fields=['farm', 'date'], name='productions_farm_id_116f16_idx'), models.Index(fields=['date', 'session'], name='productions_date_be68d3_idx')],
                'unique_together': {('animal', 'date', 'session')},
            },
        ),
    ]
