# Generated by Django 6.0.4 on 2026-06-24 17:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('farms', '0001_initial'),
        ('productions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MilkProductionSummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('total_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total quantity (liters)')),
                ('total_animals_milked', models.PositiveIntegerField(default=0, verbose_name='total animals milked')),
                ('average_quantity_per_animal', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='average quantity per animal')),
                ('morning_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='morning quantity (liters)')),
                ('afternoon_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='afternoon quantity (liters)')),
                ('evening_quantity', models.DecimalField(decimal_places=2, default=0, max_digits=15, validators=[django.core.validators.MinValueValidator(0)], verbose_name='evening quantity (liters)')),
                ('average_fat', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average fat percentage')),
                ('average_snf', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average SNF percentage')),
                ('total_value', models.DecimalField(decimal_places=2, default=0, max_digits=20, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total value')),
                ('average_price_per_liter', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='average price per liter')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='daily_summaries', to='farms.farm', verbose_name='farm')),
            ],
            options={
                'verbose_name': 'milk production summary',
                'verbose_name_plural': 'milk production summaries',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['farm', 'date'], name='productions_farm_id_1b2ff1_idx')],
            },
        ),
    ]
