# Generated by Django 6.0.4 on 2026-06-13 17:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('animals', '0002_breedingrecord_calvingrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_important', models.BooleanField(default=False, verbose_name='is important')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='animals.animal', verbose_name='animal')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_animal_notes', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
            ],
            options={
                'verbose_name': 'animal note',
                'verbose_name_plural': 'animal notes',
                'ordering': ['is_important', '-created_at'],
                'indexes': [models.Index(fields=['animal'], name='animals_ani_animal__107efd_idx'), models.Index(fields=['created_at'], name='animals_ani_created_32f82a_idx')],
            },
        ),
    ]
