# Generated by Django 6.0.4 on 2026-06-10 08:59

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='farm name')),
                ('code', models.CharField(blank=True, max_length=50, unique=True, verbose_name='farm code')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('farm_type', models.CharField(choices=[('dairy', 'Dairy Farm'), ('mixed', 'Mixed Farming'), ('organic', 'Organic Dairy'), ('commercial', 'Commercial Dairy')], default='dairy', max_length=20, verbose_name='farm type')),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('suspended', 'Suspended')], default='active', max_length=20, verbose_name='status')),
                ('address', models.TextField(verbose_name='address')),
                ('city', models.CharField(max_length=100, verbose_name='city')),
                ('state', models.CharField(max_length=100, verbose_name='state')),
                ('country', models.CharField(default='India', max_length=100, verbose_name='country')),
                ('pincode', models.CharField(max_length=20, verbose_name='pincode')),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-90)], verbose_name='latitude')),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True, validators=[django.core.validators.MinValueValidator(-180)], verbose_name='longitude')),
                ('contact_person', models.CharField(blank=True, max_length=150, verbose_name='contact person')),
                ('contact_phone', models.CharField(blank=True, max_length=20, verbose_name='contact phone')),
                ('contact_email', models.EmailField(blank=True, max_length=254, verbose_name='contact email')),
                ('total_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='total area (acres)')),
                ('grazing_area', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='grazing area (acres)')),
                ('built_up_area', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='built-up area (sq ft)')),
                ('max_animals', models.PositiveIntegerField(default=0, verbose_name='maximum animals')),
                ('current_animals', models.PositiveIntegerField(default=0, verbose_name='current animals')),
                ('has_milking_parlor', models.BooleanField(default=False, verbose_name='has milking parlor')),
                ('has_cold_storage', models.BooleanField(default=False, verbose_name='has cold storage')),
                ('has_veterinary_facility', models.BooleanField(default=False, verbose_name='has veterinary facility')),
                ('has_feed_storage', models.BooleanField(default=False, verbose_name='has feed storage')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('owner', models.ForeignKey(limit_choices_to={'role': 'owner'}, on_delete=django.db.models.deletion.CASCADE, related_name='owned_farms', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'farm',
                'verbose_name_plural': 'farms',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(choices=[('registration', 'Registration Certificate'), ('license', 'License'), ('insurance', 'Insurance'), ('land_title', 'Land Title'), ('permit', 'Permit'), ('other', 'Other')], max_length=20, verbose_name='document type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('file', models.FileField(upload_to='farm_documents/', verbose_name='file')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('issue_date', models.DateField(blank=True, null=True, verbose_name='issue date')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='expiry date')),
                ('document_number', models.CharField(blank=True, max_length=100, verbose_name='document number')),
                ('is_verified', models.BooleanField(default=False, verbose_name='is verified')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='uploaded at')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='farms.farm', verbose_name='farm')),
            ],
            options={
                'verbose_name': 'farm document',
                'verbose_name_plural': 'farm documents',
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('content', models.TextField(verbose_name='content')),
                ('is_important', models.BooleanField(default=False, verbose_name='is important')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='farm_notes', to=settings.AUTH_USER_MODEL, verbose_name='created by')),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='farms.farm', verbose_name='farm')),
            ],
            options={
                'verbose_name': 'farm note',
                'verbose_name_plural': 'farm notes',
                'ordering': ['-is_important', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FarmSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('milking_sessions_per_day', models.PositiveIntegerField(default=2, verbose_name='milking sessions per day')),
                ('default_milk_price', models.DecimalField(decimal_places=2, default=50.0, max_digits=10, verbose_name='default milk price per liter')),
                ('low_inventory_threshold', models.PositiveIntegerField(default=20, verbose_name='low inventory threshold (%)')),
                ('animal_health_alert_days', models.PositiveIntegerField(default=30, verbose_name='animal health alert days')),
                ('email_notifications', models.BooleanField(default=True, verbose_name='email notifications')),
                ('sms_notifications', models.BooleanField(default=False, verbose_name='SMS notifications')),
                ('currency', models.CharField(default='INR', max_length=10, verbose_name='currency')),
                ('weight_unit', models.CharField(default='kg', max_length=10, verbose_name='weight unit')),
                ('volume_unit', models.CharField(default='liter', max_length=10, verbose_name='volume unit')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('farm', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='farms.farm', verbose_name='farm')),
            ],
            options={
                'verbose_name': 'farm settings',
                'verbose_name_plural': 'farm settings',
            },
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['owner'], name='farms_farm_owner_i_194369_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['status'], name='farms_farm_status_b1361c_idx'),
        ),
        migrations.AddIndex(
            model_name='farm',
            index=models.Index(fields=['code'], name='farms_farm_code_c06f9d_idx'),
        ),
    ]
